### PR TITLE
Updated from network content collector

### PR DESCRIPTION
**Pull request by CaptTrews**
Depends-On: https://github.com/ansible/ansible/pull/60947
Signed-off-by: CaptTrews <capttrews@gmail.com>

### CODE REVIEW

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now c0549b8e9e0116d8ba72717ed38bc306e0a57bbd

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 3fe30a9c1bc6fe6220cc047631ad5a646c426553

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now ce58a4985bd3929f33e02c748cfb29a995a408b7

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 364b759d6de58044493caeec40b24f2cd4129522

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 35528ad0c5518a54e8f0782005ca891201eecd37

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 2019f0b07076ca58ddb9e9ac0be65402b477eec1

**Pull request merged**
