### PR TITLE
Updated from network content collector

### PR DESCRIPTION
**Pull request by CaptTrews**
Signed-off-by: CaptTrews <capttrews@gmail.com>
Depends-On: https://github.com/ansible/ansible/pull/62596

### CODE REVIEW

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now c41ef1c487aeacea7a7be94470dca3454add031c

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 1602e697c0516ab0369cdb1d99babf8286400290

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now ebe0ffadcc6d70c1a033987c9ab7b6c37f579e93

**Comment by pabelanger** [comment]
recheck

**Pull request merged**
