### PR TITLE
Updated from network content collector

### PR DESCRIPTION
**Pull request by CaptTrews**
Signed-off-by: CaptTrews <capttrews@gmail.com>

### CODE REVIEW

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 5df79c9c18665eb5151b3053285231f7898a1c4f

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now a4bbcbdf9314135b2d639d8393b2ab7cc33369ab

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now c8fac16d25a850e6bf1988722685844792713f3a

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 8c3887e13efc14a80a9f809acb7b1d257a56bdbf

**Pull request merged**
