### PR TITLE
Updated from network content collector

### PR DESCRIPTION
**Pull request by CaptTrews**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/306
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/309
Depends-On: https://github.com/ansible-network/ansible_collections.ansible.netcommon/pull/12
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/312
Depends-On: https://github.com/ansible-network/network_collections_migration/pull/46
Signed-off-by: CaptTrews <capttrews@gmail.com>

### CODE REVIEW

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now ed26868692aeae47c31d6a0df05234a77395e1be

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now d236dc3ae449cb15bf39ded07e19de8fcf4ddea3

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now df8d26962073715080257b74020770e69a7e05d0

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now d2a4a4ac96d1b5b8de18866fee6f885ba0db2f69

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 3b4634ac2c05c9cae91e4d78796b7498ec2a0393

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 6608988174885917d0103e1bd273569cb4af0272

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 8e47bf2e9a37a663d8112a1df1764a35669c3566

**Pull request merged**
