### PR TITLE
Updated from network content collector

### PR DESCRIPTION
**Pull request by CaptTrews**
Depends-On: https://github.com/ansible-network/ansible_collections.cisco.iosxr/pull/50
Signed-off-by: CaptTrews <capttrews@gmail.com>

### CODE REVIEW

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 4f6732885d8cf7984d16fdee77906f6e13f2afd2

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now d642a75a7e2e49782edb694d9bd891e8301cc182

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 48305b3612bd1cc9b4f448c73a835c5f212156d0

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 571ca670aba3935f57426a51b066ab98fc5e6e58

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now eda1e60590da9b09fac39a1dcba0c2981ab0f961

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 4acf449671108d4f9474627fb0d247f6f2e3b9e5

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 345aef080de0a641756483beb2986e82cf7a73a3

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now ad4c4850d664a7fce0ddec6f35df79b291a42fc5

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 070fbb956bd9ca9da3f0d1593684e1abf28c7ce0

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now d81bcca7c02d712d364c51ea3f903325495baaf5

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now d500abe6e20ad6d7804f3ff9e9fda65cab55d5e7

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 92a015a7b3726006695e280bca8121d8ad91b486

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 046bcf3d4677c6568345ff0cfb93e76061b0e360

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 203637d079516e9dc16ff9bd45417b3ed6b57d69

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 2f78d2e27b324044182a95c92dbd03d45c465cbf

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 1e4ae10c1e12b8226c1feceec9c8f71b931eb8e1

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 5ee7158f704b3f04b2e297f77a15362aa1c22ff9

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 4f095d771990b615c453ca1e7dd34d2976e2736d

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 031df14af96cacc669a217de56366ed35b6809cd

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 03602b13f5f4111b01083f1ae4102ef9e9535c68

**Pull request merged**
